### ISSUE TITLE
GetArenaPostGameCarnageReport: JSON integer is too large or small for an Int32

### ISSUE THREAD

**Issue by gpez-git** [glitch100/Halo-API#3]
Looks similar to issue #2.  

GET /stats/h5/arena/matches/c44a03be-36c3-4327-8946-7dab19e91c1d HTTP/1.1

Additional information: JSON integer 4248941445 is too large or small for an Int32. Path 'PlayerStats[4].MetaCommendationDeltas[0].PreviousMetRequirements[0].Data1', line 1, position 16559.

Sure enough, all of those values are very large.  Not sure what the data type should be, but almost certainly not an Int32 :)

**Comment by gpez-git** [comment]
Looks like maybe you already ran in to this issue.

http://stackoverflow.com/questions/33910071/jsonconvert-deserializeobject-throws-exception-on-uint64-returns-null-object

One possible solution is just update MetRequirements to strings?

namespace HaloEzAPI.Model.Response.Stats
{
    public class MetRequirement
    {
        public string Data1 { get; set; }
        public string Data2 { get; set; }
        public string Data3 { get; set; }
        public string Data4 { get; set; }
    }
}

**Comment by gpez-git** [comment]
Confirmed with the change to string that the example earlier deseralizes.  Not sure if it is the correct fix but happy to submit.

**Comment by prom3theu5** [comment]
Shouldn't they just be uint? 
Strings seem so dirty here

**Comment by gpez-git** [comment]
I agree but there are values too big even for ulongs.

**Comment by glitch100** [comment]
@prom3theu5  
@gpeszek 

Thanks for notifying me of the issue, naturally I have a number of references that are around that need to changed from `int` to `uint`, I have tried to catch most of them but they will crop up.

I will get a fix out for this today. Annoying that their API just doesn't return something else.

**Comment by glitch100** [comment]
This should be resolved with https://github.com/glitch100/Halo-API/commit/943784a4d6929d203e8fc9a47cc14fb4ccd78e9e

**Comment by gpez-git** [comment]
@glitch100 

Thanks Jon!
